<?php

declare(strict_types=1);

namespace App\Services;

use App\Repositories\IncidentRepository;
use PDO;

final class ExportService extends BaseService
{
    private IncidentRepository $incidentRepo;

    public function __construct(IncidentRepository $incidentRepo)
    {
        parent::__construct();
        $this->incidentRepo = $incidentRepo;
    }

    /**
     * Generates a CSV export of incidents based on filters.
     * Returns the absolute path to the generated temporary file.
     */
    public function generateIncidentsCsv(array $filters = []): string
    {
        // Build query based on filters
        $pdo = $this->incidentRepo->getConnection();
        $sql = "SELECT i.reference_number, c.name as category, i.title, i.status, 
                       i.priority, i.created_at, u.full_name as reported_by
                FROM incidents i
                LEFT JOIN incident_categories c ON i.category_id = c.id
                LEFT JOIN users u ON i.citizen_id = u.id
                WHERE i.deleted_at IS NULL";
                
        // In a real app, bind $filters dynamically here...
        $sql .= " ORDER BY i.created_at DESC";

        $stmt = $pdo->prepare($sql);
        $stmt->execute();

        // Create temporary file
        $tempFile = tempnam(sys_get_temp_dir(), 'gcirms_export_');
        $file = fopen($tempFile, 'w');

        // Add UTF-8 BOM for Excel compatibility
        fputs($file, $bom = (chr(0xEF) . chr(0xBB) . chr(0xBF)));

        // Write Headers
        fputcsv($file, [
            'Reference Number', 
            'Category', 
            'Title', 
            'Status', 
            'Priority', 
            'Reported By', 
            'Date Reported'
        ]);

        // Write Data Rows
        while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
            fputcsv($file, [
                $row['reference_number'],
                $row['category'] ?? 'Unknown',
                $row['title'],
                ucwords(str_replace('_', ' ', $row['status'])),
                ucfirst($row['priority']),
                $row['reported_by'] ?? 'Anonymous',
                $row['created_at']
            ]);
        }

        fclose($file);
        
        return $tempFile;
    }

    /**
     * Stub for PDF generation (Requires FPDF/TCPDF via Composer).
     * Generates an official acknowledgement receipt.
     */
    public function generateAcknowledgementPdf(array $incidentData): string
    {
        // For now, since composer extensions are blocked, we generate a simple HTML/TXT fallback
        // that simulates the behavior of a generated PDF file.
        
        $tempFile = tempnam(sys_get_temp_dir(), 'gcirms_receipt_') . '.html';
        
        $html = "
        <div style='font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; border: 1px solid #ddd;'>
            <div style='text-align: center; border-bottom: 2px solid #1a3a6b; padding-bottom: 20px; margin-bottom: 20px;'>
                <h1 style='color: #1a3a6b;'>GOVERNMENT OF TANZANIA</h1>
                <h2>Civic Incident Acknowledgement Receipt</h2>
            </div>
            
            <table style='width: 100%; border-collapse: collapse;'>
                <tr>
                    <td style='padding: 10px; border: 1px solid #eee;'><strong>Reference No:</strong></td>
                    <td style='padding: 10px; border: 1px solid #eee; font-weight: bold;'>" . htmlspecialchars($incidentData['reference_number']) . "</td>
                </tr>
                <tr>
                    <td style='padding: 10px; border: 1px solid #eee;'><strong>Date Reported:</strong></td>
                    <td style='padding: 10px; border: 1px solid #eee;'>" . htmlspecialchars($incidentData['created_at']) . "</td>
                </tr>
                <tr>
                    <td style='padding: 10px; border: 1px solid #eee;'><strong>Title:</strong></td>
                    <td style='padding: 10px; border: 1px solid #eee;'>" . htmlspecialchars($incidentData['title']) . "</td>
                </tr>
                <tr>
                    <td style='padding: 10px; border: 1px solid #eee;'><strong>Status:</strong></td>
                    <td style='padding: 10px; border: 1px solid #eee; text-transform: capitalize;'>" . str_replace('_', ' ', $incidentData['status']) . "</td>
                </tr>
            </table>
            
            <div style='margin-top: 40px; padding: 15px; background-color: #f8f9fa; border-left: 4px solid #17a2b8;'>
                <p>Thank you for your report. Your incident has been logged into the GCIRMS platform and will be routed to the appropriate government agency for resolution.</p>
                <p>Please keep this reference number secure to track the progress of your report.</p>
            </div>
            
            <div style='margin-top: 50px; text-align: center; font-size: 12px; color: #777;'>
                Generated by Government-Scale Civic Incident Reporting and Management System (GCIRMS)
            </div>
        </div>";

        file_put_contents($tempFile, $html);
        
        return $tempFile;
    }
}
